base_config: base_config.yaml
model:
  num_layers: 8
  future_horizon: 3
  d_embed: 768
data:
  future_horizon: 1
  num_full_res_frames: 10
  history_prefix_frames: 0
training:
  objective: residue_centric
  res_ce_weight: 2.0
  res_js_weight: 0.0
  learning_rate: 0.0001
  label_smoothing: 0.02
  scheduled_sampling_p: 0.0
  use_scheduler: true
  estimated_steps_per_epoch: 3125
  warmup_steps: 1000
  max_epochs: 10
  grad_accum_steps: 32
experiment:
  run_name: sweep_K10_D768_future_horizon1_L8_CE2.0_JS0.0_SS0.0_7060
  tags:
  - residue_centric
  - full_dataset
  - sweep
